const TOKEN_CYBERSOFT =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJCb290Y2FtcCAyOSIsIkhldEhhblN0cmluZyI6IjE5LzAxLzIwMjMiLCJIZXRIYW5UaW1lIjoiMTY3NDA4NjQwMDAwMCIsIm5iZiI6MTY0NTk4MTIwMCwiZXhwIjoxNjc0MjM0MDAwfQ.YESwad1hPeFZLi1alQUINpqBwiG-eLBBTADYwGZBfQc";

// console.log(process.env.REACT_APP_BASE_URL);
const BASE_URL = process.env.REACT_APP_BASE_URL;

const USER_INFO_KEY = "USER_INFO_KEY";

const GROUP_ID = "GP03";

export { TOKEN_CYBERSOFT, BASE_URL, USER_INFO_KEY, GROUP_ID };
